export enum UserRole {
  DESENVOLVEDOR_JUNIOR = 'Desenvolvedor Júnior',
  DESENVOLVEDOR_PLENO = 'Desenvolvedor Pleno',
  DESENVOLVEDOR_SENIOR = 'Desenvolvedor Sênior',
  TECH_LEAD = 'Tech Lead',
  ARQUITETO_SOFTWARE = 'Arquiteto de Software',
  ENGENHEIRO_DEVOPS = 'Engenheiro DevOps',
  ENGENHEIRO_DADOS = 'Engenheiro de Dados',
  CIENTISTA_DADOS = 'Cientista de Dados',
  ANALISTA_QA = 'Analista de QA',
  ENGENHEIRO_QA = 'Engenheiro de QA',
  PRODUCT_OWNER = 'Product Owner',
  SCRUM_MASTER = 'Scrum Master',
  GERENTE_PROJETOS = 'Gerente de Projetos',
  ANALISTA_SISTEMAS = 'Analista de Sistemas',
  ADMINISTRADOR_SISTEMAS = 'Administrador de Sistemas',
  ADMINISTRADOR_REDES = 'Administrador de Redes',
  ANALISTA_SEGURANCA = 'Analista de Segurança',
  DESIGNER_UI_UX = 'Designer UI/UX',
  ANALISTA_SUPORTE = 'Analista de Suporte',
  CTO = 'CTO',
  ESTAGIARIO = 'Estagiário',
  OUTRO = 'Outro',
}
